# Change these first
owner: apgyorfi # Your GitHub organization or username, where this repository lives
repo: szkkk-monitor # The name of this repository

runner: "[self-hosted, linux, X64]"

sites:
  - name: Fehérvári program
    url: https://www.fehervariprogram.hu
  - name: Fehérvári program jegyrendszer
    url: https://fehervariprogram.hu/jegy
  - name: Tele Élettel programportál
    url: https://teleelettel.hu
  - name: Barátság mozi honlap
    url: https://baratsagmozi.hu
  - name: Barátság mozi jegyrendszer
    url: https://musor.baratsagmozi.hu
  - name: Királyi napok
    url: https://kiralyinapok.szekesfehervar.hu
  - name: Diáknapok
    url: https://diaknapok.hu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /szkkk-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SZKKK MONITOR
  introTitle: ""
  introMessage: 
  # navbar:
    # - title: GitHub
    # href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "50 23 * * *"

i18n:
  activeIncidents: Aktív incidensek
  allSystemsOperational: Minden rendszer működik
  incidentReport: "Incidens #$NUMBER jelentés →"
  activeIncidentSummary: Megnyitva: $DATE, hozzászólások: $POSTS
  incidentTitle: Incidens $NUMBER részletei
  incidentDetails: Incidens részletei
  incidentFixed: Javítva
  incidentOngoing: Folyamatban
  incidentOpenedAt: Megnyitva ekkor:
  incidentClosedAt: Lezárva ekkor:
  incidentViewOnGitHub: Megtekintés és feliratkozás a GitHubon
  incidentCommentSummary: Közzétéve $DATE – $AUTHOR
  incidentBack: ← Vissza az összes incidenshez
  pastIncidents: Korábbi incidensek
  pastIncidentsResolved: Megoldva $MINUTES perc alatt, $POSTS hozzászólással
  liveStatus: Élő állapot
  overallUptime: "Összesített üzemidő: $UPTIME"
  overallUptimeTitle: Összesített üzemidő
  averageResponseTime: "Átlagos válaszidő: $TIME ms"
  averageResponseTimeTitle: Átlagos válaszidő
  sevelDayResponseTime: 7 napos válaszidő
  responseTimeMs: Válaszidő (ms)
  up: Elérhető
  down: Nem elérhető
  degraded: Csökkent működés
  ms: ms
  loading: Betöltés…
  navGitHub: GitHub
  footer: Ez az oldal [nyílt forráskódú]($REPO), a [Upptime](https://upptime.js.org) által működtetve
  rateLimitExceededTitle: Lekérési korlát túllépve
  rateLimitExceededIntro: Túllépted az óránkénti lekérési korlátot, ezért várnod kell, mielőtt újra elérheted ezt az oldalt. Alternatív megoldásként megadhatod a GitHub személyes hozzáférési tokenedet.
  rateLimitExceededWhatDoesErrorMean: Mit jelent ez a hiba?
  rateLimitExceededErrorMeaning: Ez az oldal a GitHub API-t használja az oldalak állapotának valós idejű elérésére. Alapértelmezés szerint a GitHub minden IP-cím számára óránként 60 lekérést engedélyez, amit már felhasználtál.
  rateLimitExceededErrorHowCanFix: Hogyan oldható meg?
  rateLimitExceededErrorFix: Várhatsz egy órát, és a limit visszaáll. Vagy megadhatsz egy GitHub hozzáférési tokent, amivel óránként 5000 lekérést kapsz.
  rateLimitExceededGeneratePAT: Tudj meg többet a hozzáférési token létrehozásáról
  rateLimitExceededHasSet: A személyes hozzáférési token be van állítva.
  rateLimitExceededRemoveToken: Token eltávolítása
  rateLimitExceededGitHubPAT: GitHub személyes hozzáférési token
  rateLimitExceededCopyPastePAT: Illeszd be a tokened
  rateLimitExceededSaveToken: Token mentése
  errorTitle: Hiba történt
  errorIntro: Hiba történt az állapotadatok lekérdezésekor.
  errorText: Próbáld meg újra néhány pillanat múlva.
  errorHome: Vissza a főoldalra
  pastScheduledMaintenance: Korábbi ütemezett karbantartások
  scheduledMaintenance: Ütemezett karbantartás
  scheduledMaintenanceSummaryStarted: Elindult: $DATE, időtartam: $DURATION perc
  scheduledMaintenanceSummaryStarts: Kezdés: $DATE, várható időtartam: $DURATION perc
  startedAt: Kezdés ideje
  startsAt: Kezdődik
  duration: Időtartam
  durationMin: $DURATION perc
  incidentCompleted: Befejezve
  incidentScheduled: Ütemezve
  duration24H: 24 óra
  duration7D: 7 nap
  duration30D: 30 nap
  duration1Y: 1 év
  durationAll: összes
  locale: hu-HU

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
