# Change these first
owner: apgyorfi # Your GitHub organization or username, where this repository lives
repo: szkkk-monitor # The name of this repository

runner: "[self-hosted, linux, X64]"

skipDeleteIssues: true

sites:
  - name: Fehérvári program
    url: https://www.fehervariprogram.hu
  - name: Fehérvári program jegyrendszer
    url: https://fehervariprogram.hu/jegy
  - name: Tele Élettel programportál
    url: https://teleelettel.hu
  - name: Barátság mozi honlap
    url: https://baratsagmozi.hu
    maxResponseTime: 5000
  - name: Barátság mozi jegyrendszer
    url: https://musor.baratsagmozi.hu
  - name: Királyi napok
    url: https://kiralyinapok.szekesfehervar.hu
  - name: Diáknapok
    url: https://diaknapok.hu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /szkkk-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SZKKK MONITOR
  introTitle: ""
  introMessage: 
  # navbar:
    # - title: GitHub
    # href: https://github.com/$OWNER/$REPO

# workflowSchedule:
#  graphs: "0 0 * * *"
#  responseTime: "0 23 * * *"
#  staticSite: "0 1 * * *"
#  summary: "0 0 * * *"
#  updateTemplate: "0 0 * * *"
#  updates: "0 3 * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

#commitMessages:
 # commitAuthorName: "upptime-bot"
 # commitAuthorEmail: "hello@apgyorfi.dev"
